config/routes.rb
First::Application.routes.draw do
  resources :people

  get "home/index"

  

end

app/models/person.rb
class Person < ActiveRecord::Base
  
  validate :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end
  
  def new
    @person = Person.new
  end
  
  def create
    @person = Person.new(person_params)
    
    if @person.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end
  
  def show
    @person = Person.where(id:params[:id]).first
  end
  
  def edit
    @person = Person.where(id:params[:id]).first
  end
  
  def update
    @person = Person.where(id:params[:id]).first
    
    if @person.update_attributes(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end
  
  private
  def person_params
    params.require(:person).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<small><%= 2 * 2 %></small>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>First</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
</p>
  <%= f.text_field :bod %>
  <%= f.text_field :weight %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p>
  <%= link_to 'New', new_person_path %>
</p>
<ul>
  <%- @people.each do |person| %>
    <li>
      <%= person.name %>
  </li>
  <%- end %>
</ul>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Name:<br/>
  <%= @person.name %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>